/*
 * Transactions API
 *  The transactions API lets you view your transactions, accounts, and statements. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developer-access@brex.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.CardTransactionMerchant;
import com.konfigthis.client.model.CardTransactionType;
import com.konfigthis.client.model.Money;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.LocalDate;
import java.util.HashMap;
import java.util.Map;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CardTransaction
 */
public class CardTransactionTest {
    private final CardTransaction model = new CardTransaction();

    /**
     * Model tests for CardTransaction
     */
    @Test
    public void testCardTransaction() {
        // TODO: test CardTransaction
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'cardId'
     */
    @Test
    public void cardIdTest() {
        // TODO: test cardId
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'initiatedAtDate'
     */
    @Test
    public void initiatedAtDateTest() {
        // TODO: test initiatedAtDate
    }

    /**
     * Test the property 'postedAtDate'
     */
    @Test
    public void postedAtDateTest() {
        // TODO: test postedAtDate
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'merchant'
     */
    @Test
    public void merchantTest() {
        // TODO: test merchant
    }

    /**
     * Test the property 'cardMetadata'
     */
    @Test
    public void cardMetadataTest() {
        // TODO: test cardMetadata
    }

    /**
     * Test the property 'expenseId'
     */
    @Test
    public void expenseIdTest() {
        // TODO: test expenseId
    }

}
