/*
 * Transactions API
 *  The transactions API lets you view your transactions, accounts, and statements. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developer-access@brex.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CardTransactionMerchant
 */
public class CardTransactionMerchantTest {
    private final CardTransactionMerchant model = new CardTransactionMerchant();

    /**
     * Model tests for CardTransactionMerchant
     */
    @Test
    public void testCardTransactionMerchant() {
        // TODO: test CardTransactionMerchant
    }

    /**
     * Test the property 'rawDescriptor'
     */
    @Test
    public void rawDescriptorTest() {
        // TODO: test rawDescriptor
    }

    /**
     * Test the property 'mcc'
     */
    @Test
    public void mccTest() {
        // TODO: test mcc
    }

}
