/*
 * Transactions API
 *  The transactions API lets you view your transactions, accounts, and statements. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developer-access@brex.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Money;
import com.konfigthis.client.model.Status;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CashAccount
 */
public class CashAccountTest {
    private final CashAccount model = new CashAccount();

    /**
     * Model tests for CashAccount
     */
    @Test
    public void testCashAccount() {
        // TODO: test CashAccount
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'currentBalance'
     */
    @Test
    public void currentBalanceTest() {
        // TODO: test currentBalance
    }

    /**
     * Test the property 'availableBalance'
     */
    @Test
    public void availableBalanceTest() {
        // TODO: test availableBalance
    }

    /**
     * Test the property 'accountNumber'
     */
    @Test
    public void accountNumberTest() {
        // TODO: test accountNumber
    }

    /**
     * Test the property 'routingNumber'
     */
    @Test
    public void routingNumberTest() {
        // TODO: test routingNumber
    }

    /**
     * Test the property 'primary'
     */
    @Test
    public void primaryTest() {
        // TODO: test primary
    }

}
