/*
 * Transactions API
 *  The transactions API lets you view your transactions, accounts, and statements. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developer-access@brex.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets CardTransactionType
 */
@JsonAdapter(CardTransactionType.Adapter.class)public enum CardTransactionType {
  
  PURCHASE("PURCHASE"),
  
  REFUND("REFUND"),
  
  CHARGEBACK("CHARGEBACK"),
  
  REWARDS_CREDIT("REWARDS_CREDIT"),
  
  COLLECTION("COLLECTION"),
  
  BNPL_FEE("BNPL_FEE");

  private String value;

  CardTransactionType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static CardTransactionType fromValue(String value) {
    for (CardTransactionType b : CardTransactionType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<CardTransactionType> {
    @Override
    public void write(final JsonWriter jsonWriter, final CardTransactionType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public CardTransactionType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return CardTransactionType.fromValue(value);
    }
  }
}

