/*
 * Transactions API
 *  The transactions API lets you view your transactions, accounts, and statements. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developer-access@brex.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.CardAccountCurrentBalance;
import com.konfigthis.client.model.StatementPeriod;
import com.konfigthis.client.model.Status;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * CardAccount
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class CardAccount {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private Status status;

  public static final String SERIALIZED_NAME_CURRENT_BALANCE = "current_balance";
  @SerializedName(SERIALIZED_NAME_CURRENT_BALANCE)
  private CardAccountCurrentBalance currentBalance;

  public static final String SERIALIZED_NAME_AVAILABLE_BALANCE = "available_balance";
  @SerializedName(SERIALIZED_NAME_AVAILABLE_BALANCE)
  private CardAccountCurrentBalance availableBalance;

  public static final String SERIALIZED_NAME_ACCOUNT_LIMIT = "account_limit";
  @SerializedName(SERIALIZED_NAME_ACCOUNT_LIMIT)
  private CardAccountCurrentBalance accountLimit;

  public static final String SERIALIZED_NAME_CURRENT_STATEMENT_PERIOD = "current_statement_period";
  @SerializedName(SERIALIZED_NAME_CURRENT_STATEMENT_PERIOD)
  private StatementPeriod currentStatementPeriod;

  public CardAccount() {
  }

  public CardAccount id(String id) {
    
    
    
    
    this.id = id;
    return this;
  }

   /**
   * ID of the card account
   * @return id
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "ID of the card account")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    
    
    
    this.id = id;
  }


  public CardAccount status(Status status) {
    
    
    
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Status getStatus() {
    return status;
  }


  public void setStatus(Status status) {
    
    
    
    this.status = status;
  }


  public CardAccount currentBalance(CardAccountCurrentBalance currentBalance) {
    
    
    
    
    this.currentBalance = currentBalance;
    return this;
  }

   /**
   * Get currentBalance
   * @return currentBalance
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public CardAccountCurrentBalance getCurrentBalance() {
    return currentBalance;
  }


  public void setCurrentBalance(CardAccountCurrentBalance currentBalance) {
    
    
    
    this.currentBalance = currentBalance;
  }


  public CardAccount availableBalance(CardAccountCurrentBalance availableBalance) {
    
    
    
    
    this.availableBalance = availableBalance;
    return this;
  }

   /**
   * Get availableBalance
   * @return availableBalance
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public CardAccountCurrentBalance getAvailableBalance() {
    return availableBalance;
  }


  public void setAvailableBalance(CardAccountCurrentBalance availableBalance) {
    
    
    
    this.availableBalance = availableBalance;
  }


  public CardAccount accountLimit(CardAccountCurrentBalance accountLimit) {
    
    
    
    
    this.accountLimit = accountLimit;
    return this;
  }

   /**
   * Get accountLimit
   * @return accountLimit
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public CardAccountCurrentBalance getAccountLimit() {
    return accountLimit;
  }


  public void setAccountLimit(CardAccountCurrentBalance accountLimit) {
    
    
    
    this.accountLimit = accountLimit;
  }


  public CardAccount currentStatementPeriod(StatementPeriod currentStatementPeriod) {
    
    
    
    
    this.currentStatementPeriod = currentStatementPeriod;
    return this;
  }

   /**
   * Get currentStatementPeriod
   * @return currentStatementPeriod
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public StatementPeriod getCurrentStatementPeriod() {
    return currentStatementPeriod;
  }


  public void setCurrentStatementPeriod(StatementPeriod currentStatementPeriod) {
    
    
    
    this.currentStatementPeriod = currentStatementPeriod;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the CardAccount instance itself
   */
  public CardAccount putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CardAccount cardAccount = (CardAccount) o;
    return Objects.equals(this.id, cardAccount.id) &&
        Objects.equals(this.status, cardAccount.status) &&
        Objects.equals(this.currentBalance, cardAccount.currentBalance) &&
        Objects.equals(this.availableBalance, cardAccount.availableBalance) &&
        Objects.equals(this.accountLimit, cardAccount.accountLimit) &&
        Objects.equals(this.currentStatementPeriod, cardAccount.currentStatementPeriod)&&
        Objects.equals(this.additionalProperties, cardAccount.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, status, currentBalance, availableBalance, accountLimit, currentStatementPeriod, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CardAccount {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    currentBalance: ").append(toIndentedString(currentBalance)).append("\n");
    sb.append("    availableBalance: ").append(toIndentedString(availableBalance)).append("\n");
    sb.append("    accountLimit: ").append(toIndentedString(accountLimit)).append("\n");
    sb.append("    currentStatementPeriod: ").append(toIndentedString(currentStatementPeriod)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("status");
    openapiFields.add("current_balance");
    openapiFields.add("available_balance");
    openapiFields.add("account_limit");
    openapiFields.add("current_statement_period");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("id");
    openapiRequiredFields.add("current_statement_period");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to CardAccount
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!CardAccount.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CardAccount is not found in the empty JSON string", CardAccount.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : CardAccount.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      // validate the optional field `status`
      if (jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) {
        Status.validateJsonObject(jsonObj.getAsJsonObject("status"));
      }
      // validate the optional field `current_balance`
      if (jsonObj.get("current_balance") != null && !jsonObj.get("current_balance").isJsonNull()) {
        CardAccountCurrentBalance.validateJsonObject(jsonObj.getAsJsonObject("current_balance"));
      }
      // validate the optional field `available_balance`
      if (jsonObj.get("available_balance") != null && !jsonObj.get("available_balance").isJsonNull()) {
        CardAccountCurrentBalance.validateJsonObject(jsonObj.getAsJsonObject("available_balance"));
      }
      // validate the optional field `account_limit`
      if (jsonObj.get("account_limit") != null && !jsonObj.get("account_limit").isJsonNull()) {
        CardAccountCurrentBalance.validateJsonObject(jsonObj.getAsJsonObject("account_limit"));
      }
      // validate the required field `current_statement_period`
      StatementPeriod.validateJsonObject(jsonObj.getAsJsonObject("current_statement_period"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CardAccount.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CardAccount' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CardAccount> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CardAccount.class));

       return (TypeAdapter<T>) new TypeAdapter<CardAccount>() {
           @Override
           public void write(JsonWriter out, CardAccount value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public CardAccount read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             CardAccount instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of CardAccount given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of CardAccount
  * @throws IOException if the JSON string is invalid with respect to CardAccount
  */
  public static CardAccount fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CardAccount.class);
  }

 /**
  * Convert an instance of CardAccount to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

