/*
 * Transactions API
 *  The transactions API lets you view your transactions, accounts, and statements. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developer-access@brex.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import java.time.OffsetDateTime;
import com.konfigthis.client.model.PageCardTransaction;
import com.konfigthis.client.model.PageCashTransaction;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TransactionsApi
 */
@Disabled
public class TransactionsApiTest {

    private static TransactionsApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new TransactionsApi(apiClient);
    }

    /**
     *  List transactions for all card accounts. 
     *
     *  This endpoint lists all settled transactions for all card accounts. Regular users may only fetch their own \&quot;PURCHASE\&quot;,\&quot;REFUND\&quot; and \&quot;CHARGEBACK\&quot; settled transactions. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listAllCardTransactionsTest() throws ApiException {
        String cursor = null;
        Integer limit = null;
        List<String> userIds = null;
        OffsetDateTime postedAtStart = null;
        List<String> expand = null;
        PageCardTransaction response = api.listAllCardTransactions()
                .cursor(cursor)
                .limit(limit)
                .userIds(userIds)
                .postedAtStart(postedAtStart)
                .expand(expand)
                .execute();
        // TODO: test validations
    }

    /**
     *  List transactions for the selected cash account. 
     *
     *  This endpoint lists all transactions for the cash account with the selected ID. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listByIdTest() throws ApiException {
        String id = null;
        String cursor = null;
        Integer limit = null;
        OffsetDateTime postedAtStart = null;
        PageCashTransaction response = api.listById(id)
                .cursor(cursor)
                .limit(limit)
                .postedAtStart(postedAtStart)
                .execute();
        // TODO: test validations
    }

}
